version: '3.2'

services:

  mysql:
    image: ryanwu1994/solar_sql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - dashboard

  crawler:
    image: ryanwu1994/solar_crawler:latest
    container_name: crawler
    restart: always
    depends_on:
      - mysql
    links:
      - mysql:${MYSQL_HOST}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_TABLE: ${MYSQL_TABLE}
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - dashboard

  api:
    image: ryanwu1994/solar_api:latest
    container_name: api
    restart: always
    depends_on:
      - mysql
      - crawler
    links:
      - mysql:${MYSQL_HOST}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_TABLE: ${MYSQL_TABLE}
    volumes: 
      - /etc/localtime:/etc/localtime
    ports:
      - 5000:5000
    networks:
      - dashboard

  web:
    image: nginx:1.19.6
    container_name: web
    restart: always
    depends_on:
      - mysql
      - crawler
      - api
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_TABLE: ${MYSQL_TABLE}
    volumes:
      - /etc/localtime:/etc/localtime
      - ./web/html:/usr/share/nginx/html
      - ./web/js://usr/share/nginx/js
    ports:
      - 8080:80
    networks:
      - dashboard

networks:
  dashboard:
    driver: bridge
