version: '3.0'

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 1qaz@WSX
       MYSQL_DATABASE: solar
       MYSQL_USER: ryan
       MYSQL_PASSWORD: Aa123456
    ports:
     - 3306:3306

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
